import fresh_tomatoes
import media

Dangal=media.Movie("Dangal","Former wrestler Mahavir Singh Phogat (Aamir Khan) trains young daughters Geeta (Fatima Sana Shaikh) and Babita (Sanya Malhotra) to follow in his footsteps and become world-class grapplers.","http://t3.gstatic.com/images?q=tbn:ANd9GcQIXnFlBKGWT1ByyIu3qfxX6opQX6BmeeU_qsiE3X8rX9ZRr63r","https://www.youtube.com/watch?v=x_7YlGv9u1g&ab_channel=UTVMotionPictures","9.2")
Passengers=media.Movie("Passengers","On a routine journey through space to a new home, two passengers, sleeping in suspended animation, are awakened 90 years too early when their ship malfunctions. As Jim and Aurora face living the rest of their lives on board, with every luxury they could ever ask for, they begin to fall for each other, unable to deny their intense attraction... until they discover the ship is in grave danger. With the lives of 5000 sleeping passengers at stake, only Jim and Aurora can save them all.","http://t3.gstatic.com/images?q=tbn:ANd9GcQvqid_rbEby5j_XkVnSdwWgvSTiX9Np1I6iTJPJWYZFCBOPe4w","https://www.youtube.com/watch?v=7BWWWQzTpNU","7")
Assassin=media.Movie("Assassin's Creed","Through a revolutionary technology that unlocks his genetic memories, Callum Lynch experiences the adventures of his ancestor, Aguilar, in 15th Century Spain. Callum discovers he is descended from a mysterious secret society, the Assassins, and amasses incredible knowledge and skills to take on the oppressive and powerful Templar organization in the present day.","http://t0.gstatic.com/images?q=tbn:ANd9GcQZhf2PJ2QIZozV2ZkwQxF4smGdlGP8v0VrhF1T-7kBppS4ztzn","https://www.youtube.com/watch?v=gfJVoF5ko1Y","6.7");
LivebyNight=media.Movie("Live by Night","It's the Roaring `20s and Prohibition hasn't stopped the flow of booze in an underground network of gangster-run speakeasies. The opportunity to gain power and money is there for any man with enough ambition and nerve, and Joe Coughlin, the son of the Boston Police superintendent, long ago turned his back on his strict upbringing for the spoils of being an outlaw. But even among criminals there are rules, and Joe breaks a big one: crossing a powerful mob boss by stealing his money and his moll.","http://t3.gstatic.com/images?q=tbn:ANd9GcQyDgzA7Q3OZ4quuoFkSPxx8qPhCDdetEdvNpxu_lr6k216GYJS","https://www.youtube.com/watch?v=CtFZcAuH-qI&t=79s&ab_channel=WarnerBros.Pictures","7.8")
CollateralBeauty=media.Movie("Collateral Beauty","When a successful New York advertising executive (Will Smith) suffers a great tragedy, he retreats from life. While his concerned friends try desperately to reconnect with him, he seeks answers from the universe by writing letters to Love, Time and Death. When his notes bring unexpected personal responses, he begins to understand how these constants interlock in a life fully lived and how even the deepest loss can reveal moments of meaning and beauty.","http://t0.gstatic.com/images?q=tbn:ANd9GcQdy_GMaxhJJGUvGFwoD4fo-zrttMDGEZRCDeayxC4_rO2JFLq9","https://www.youtube.com/watch?v=2ik3-q1zxik","6.2")
RogueOne=media.Movie("Rogue One","Former scientist Galen Erso lives on a farm with his wife and young daughter Jyn. His peaceful existence comes crashing down when the evil Orson Krennic takes him away from his beloved family. Many years later, Galen is now the Empire's lead engineer for the most powerful weapon in the galaxy, the Death Star. Knowing that her father holds the key to its destruction, a vengeful Jyn joins forces with a spy and other resistance fighters to steal the space station's plans for the Rebel Alliance.","http://t0.gstatic.com/images?q=tbn:ANd9GcQ0S5JQhVplHbw7O6nt7Q0r23Bssl9UNzC-z3zy1r45_eLUB43l","https://www.youtube.com/watch?v=frdj1zb9sMY","8.2")
movies = [Dangal,Passengers,Assassin,LivebyNight,CollateralBeauty,RogueOne]
fresh_tomatoes.open_movies_page(movies)